var panos = [
  {
    "title": "Chapter 1 ",
    "owner": "Breno Baldrati",
    "overlay": "overlay 1.png",
    "secondoverlay": "secondoverlay 2.jpg",
    "image": "chapter1.jpg",
    "audio": "Chapter_1_final.ogg",
    "source": "http://bit.ly/1xk9Vk1",
    "license": "Creative Commons"
  },
  {
    "title": "Chapter 2",
    "owner": " Alexandre Duret-Lutz",
    "overlay": "overlay 2.png",
    "image": "chapter2.jpg",
    "audio": "chapter_2_final.ogg",
    "source": "https://www.flickr.com/photos/gadl/406108908",
    "license": "Creative Commons"
  },
  {
      "title": "Chapter 3",
      "owner": "xx",
      "overlay": "overlay 3.png",
      "image": "chapter3.jpg",
      "audio": "chapter 3_final.ogg",
      "source": "https://www.flickr.com/photos/gadl/406108908",
      "license": "Creative Commons"
  },
  {
      "title": "Chapter 4 - Ferry Building",
      "overlay": "overlay 4.png",
      "image": "chapter4.jpg",
      "audio": "chapter_4_final.ogg",
      "source": "xx",
      "license": "Creative Commons"
  },

  {
      "title": "Chapter 5 ",
      "owner": "Breno Baldrati",
      "overlay": "overlay 5.png",
      "image": "chapter5.jpg",
      "audio": "chapter_5_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 6 ",
      "owner": "Breno Baldrati",
      "overlay": "overlay 6.png",
      "image": "chapter6.jpg",
      "audio": "chapter_6_final.ogg",
      "source": "me",
  },

  {
      "title": "Chapter 7 ",
      "owner": "Breno Baldrati",
      "overlay": "overlay 7.png",
      "image": "chapter7.jpg",
      "audio": "chapter_7_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 8 ",
      "owner": "Breno Baldrati",
      "overlay": "overlay 8.png",
      "image": "chapter8.jpg",
      "audio": "chapter_8_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 9 ",
      "owner": "Breno Baldrati",
      "overlay": "overlay 10.png",
      "image": "chapter10.jpg",
      "audio": "chapter_10_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 10 ",
      "owner": "Breno Baldrati",
      "overlay": "overlay 10.png",
      "image": "chapter10.jpg",
      "audio": "chapter_10_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 11 ",
      "owner": "Breno Baldrati",
      "overlay": "overlay 11.png",
      "image": "chapter11.jpg",
      "audio": "chapter_11_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 12 ",
      "owner": "Breno Baldrati",
      "overlay": "overlay 12.png",
      "image": "chapter12.jpg",
      "audio": "chapter_12_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 13 ",
      "owner": "Breno Baldrati",
      "overlay": "overlay 13.png",
      "image": "chapter13.jpg",
      "audio": "chapter_13_final.ogg",
      "source": "me",
      "license": "Creative Commons"
  },
  {
      "title": "Chapter 14 ",
      "owner": "Breno Baldrati",
      "overlay": "overlay 14.png",
      "image": "chapter14.jpg",
      "audio": "chapter_14_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 15 ",
      "owner": "Breno Baldrati",
      "overlay": "overlay 14.png",
      "image": "chapter14.jpg",
      "audio": "chapter_14_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 16 ",
      "owner": "Breno Baldrati",
      "overlay": "overlay 16.png",
      "image": "chapter16.jpg",
      "audio": "chapter_16_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 17 ",
      "owner": "Breno Baldrati",
      "overlay": "overlay 17.png",
      "image": "chapter17.jpg",
      "audio": "chapter_17_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 18 ",
      "owner": "Breno Baldrati",
      "overlay": "overlay 18.png",
      "image": "chapter18.jpg",
      "audio": "chapter_18_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 19",
      "owner": "Breno Baldrati",
      "overlay": "overlay 19.png",
      "image": "chapter19.jpg",
      "audio": "chapter_19_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 20",
      "owner": "Breno Baldrati",
      "overlay": "overlay 20.png",
      "image": "chapter20.jpg",
      "audio": "chapter_20_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 21",
      "owner": "Breno Baldrati",
      "overlay": "overlay 21.png",
      "image": "chapter21.jpg",
      "audio": "chapter_21_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 22",
      "owner": "Breno Baldrati",
      "overlay": "overlay 22.png",
      "image": "chapter22.jpg",
      "audio": "chapter_22_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 23",
      "owner": "Breno Baldrati",
      "overlay": "overlay 23.png",
      "image": "chapter23.jpg",
      "audio": "chapter_23_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 24",
      "owner": "Breno Baldrati",
      "overlay": "overlay 24.png",
      "image": "chapter24.jpg",
      "audio": "chapter_24_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 25",
      "owner": "Breno Baldrati",
      "overlay": "overlay 25.png",
      "image": "chapter25.jpg",
      "audio": "chapter_25_final.ogg",
      "source": "me",
  },
  {
      "title": "Chapter 26",
      "owner": "Breno Baldrati",
      "overlay": "overlay 26.png",
      "image": "chapter26.jpg",
      "audio": "chapter_26_final.ogg",
      "source": "me",
  },

];
